import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactAliasBase
	/* java */
end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.FolderArtifact
	/* java */
end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.Activity
	/* java */
end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.GenericReqNewActivity
	/* java */
end

declare DeployFolder extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactAliasBase
	
end

declare DeployActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.Activity
end

declare DeployFolderActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.Activity
end

declare ReqDownloadHttp extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.GenericReqNewActivity
end

declare ReqExtract extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.GenericReqNewActivity
end

/*
function void insertRequestArgument(RequestFact r, ArtifactRef f) {
    insert( new GenericArtifactRefAlias(r, f) );
}

function void insertRequestArgument(RequestFact r, FileArtifact f) {
    insert( new GenericFileArtifactAlias(r, f) );
}

function void insertRequestArgument(RequestFact r, FolderArtifact f) {
    insert( new GenericFolderArtifactAlias(r, f) );
}

function RequestFact insertRequest(RequestFact r) {
    insert( r );
    return r;
}

function RequestFact insertSubrequestResult(Activity a, FileArtifactAlias f) {
    insert( new FileArtifact(a, f.getFile()) );
}
*/
