import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;

///////////////////////////// java /////////////////////////////////////
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactAliasBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.ExecutableFileArtifact /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.GenericExecutableFileArtifact /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.FolderArtifact /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityRelatedFactBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.RequestRelatedFactBase /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.RequestStatusRelatedFactBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityFailedBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactBase /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactListBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.ReqDeployExecutable /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.AliasBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.UserAction /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.RequestScopedKnowledgeBase /* java */ end

declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityErrorBase /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityWarningBase /* java */ end
declare ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.features.RSKIncompatibleFeatureVersion /* java */ end

///////////////////////////// non-java /////////////////////////////////////

declare DeployFolder extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactAliasBase end

declare DeployExecutableActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end
declare DeployFolderActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end
declare BuildActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end
declare RunActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end

declare ReqDownloadHttp extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare DownloadHttpActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end


declare ReqExtract extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare ExtractActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end

declare ReqRunJava extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare RunJavaActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end
declare JavaExecutableFileArtifact extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.ExecutableFileArtifact end

declare ReqDeployFolder extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end

declare ReqGuessRunExecutable extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare GuessRunExecutableActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end
declare ExecArtifactCandidate extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactBase end
declare ExecFileArtifactList extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactListBase end
declare ExecFileArtifactListAlias extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.AliasBase end

declare ReqGuessBuildFile extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare GuessBuildFileActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end

declare ReqMvnBuild extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ReqNewActivityBase end
declare MvnBuildActivity extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity end

declare BuildFileCandidate extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactBase end
declare BuildFileArtifactList extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactListBase end
declare BuildFileArtifactListAlias extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.AliasBase end

declare BuildFile extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FileArtifactBase end
declare BuildFileMvn extends BuildFile end
declare BuildFileAnt extends BuildFile end
declare BuildFileMake extends BuildFile end

declare UserActionSelectBuildOrRun extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.UserAction
	 execArtifacts : ExecFileArtifactList;
	 buildArtifacts : BuildFileArtifactList;
end

declare UserActionSelectRunFormat extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.UserAction end

declare BuildOutputDir extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactBase end

declare MavenProjectDir extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.FolderArtifactBase end
declare MavenTargetDir extends BuildOutputDir end

declare RunFormat extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityRelatedFactBase end
declare RunFormat_Mirex_Aud_ChEst extends RunFormat end
declare RunFormat_Rest extends RunFormat end

declare RunType_Java extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityRelatedFactBase end
declare Run_JavaOptionsReady extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityRelatedFactBase end
declare Run_AppOptionsReady extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityRelatedFactBase end


declare UsrUseEncoding extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.RequestScopedKnowledgeBase
	encoding: String
end

declare RSK_JavacIncompatibleEncodings extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.RequestScopedKnowledgeBase
	encoding: String
end

declare MvnWarn_NoFileEncoding extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityWarningBase end

declare BuildErr_NoBuildOrExecFilesFound extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.ActivityErrorBase end

declare ActivityToActivityStatusCopy
	activity : ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.activity.Activity
	value : ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.utils.ActivityRelatedFact
end