import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.utils.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

query "RequestStatus for request"  (RequestFact r)
    status : RequestStatus(request == r)
end

query "RequestSubstatus for request"  (RequestFact r)
    status : RequestStatus(request == r)
end

query "RequestStatus for request refId"  (long reqRefId)
	req : RequestFact(refId == reqRefId)
    $rstatus : RequestStatus(request == req)
    substatus : java.util.LinkedList(  ) from collect ( RequestSubstatus(request == req) )
    activities : java.util.LinkedList(  ) from collect ( Activity( request == req) )
    extras : java.util.LinkedList(  ) from collect ( RequestStatusRelatedFact( rstatus == $rstatus ) )
end

query "Trace request activities"  (RequestFact r)
    activity : Activity( request == r )
    activitySuccess : ActivitySucceeded( activity == activity )
    activityError : ActivityError( activity == activity )
    activityErrorFixed : ActivityErrorFixed( activity == activity )
end

query "UserAction for refId"  (long refId)
	$object : UserAction( refId == refId )
end

query "Activity for refId"  (long refId)
	$object : Activity( refId == refId )
end

query "Get activity related facts"  (Activity a)
	$object : (ActivityRelatedFact( activity == a ) or RequestFact( parentActivity == a ))
end

query "Get request related facts"  (RequestFact req)
	$object : RequestRelatedFact( request == req )
end

query "Get request status related facts"  (RequestStatus rstat)
	$object : RequestStatusRelatedFact( rstatus == rstat )
end

query "Get activity status related facts"  (ActivityStatus astat)
	$object : ActivityStatusRelatedFact( astatus == astat )
end

query "Get userInfo facts for request"  (RequestFact request)
	$object : UserInfo( request == request )
end

query "Get activity result related facts"  (ActivityResult aresult)
	$object : ActivityResultRelatedFact( aresult == aresult )
end

query "Get root activities"  (Object ignored)
	$object : Activity( request == null )
end