import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.maven.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;

rule "NewBuild_Mvn"
	when
		BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.MAVEN)
		$b : BuildActivity()
		not MvnBuild( this == $b )
	then
		retract($b);
		insert( new MvnBuild($b) );
end

rule "BuildStatus"
	when
		$build : BuildActivity( )
		ExecStatus( activity == $build, succeeded == true )
	then
		insertLogical( new BuildSucceeded($build));
end