import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.deploy.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.maven.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "Populate deploy folder for GuessRunCommand activity"
salience -100
	when
		$r : ReqNewActivity( activityName == R.activity.GuessRunCommand )
		$a : Activity( request == $r )
		$folder : FolderArtifactAlias( request == $r )
		not FolderArtifact( activity == $a )
	then
		insert(new FolderArtifact($a, $folder);
end

rule "Populate ExecutableFileArtifact for GuessRunCommand activity"
salience -100
	when
		$r : ReqNewActivity( activityName == R.activity.GuessRunCommand )
		$a : Activity( request == $r )
		$exec : ExecutableFileArtifactAlias( request == $r )
		not ExecutableFileArtifact( activity == $a )
	then
		insert(new ExecutableFileArtifact($a, $exec);
end

rule "Evaluate run executable"
	when
		$a : Activity( activityName == R.activity.GuessRunCommand )
		$folder : FolderArtifact( activity == $a )
		not ExecutableFileArtifact( activity == $a )
	then
		ReqNewActivity r = new GenericReqNewActivity(R.activity.GuessRunExecutable, $a);
		FolderArtifactAlias f = new GenericFolderArtifactAlias(r, $folder);
		insert( f );
		insert( r );
end

rule "Propagate run executable"
	when
		$r : ReqNewActivity( activityName == R.activity.GuessRunCommand )
		$a : Activity( request == $r )
		$rre : ReqNewActivity( activityName == R.activity.GuessRunExecutable, activity == $a )
		$rdf_stat : RequestStatus( request == $rre, succeeded == true )
		$exec : ExecutableFileArtifactAlias( request == $rre )
	then
		insertLogical( new GenericExecutableFileArtifactAlias($r, $exec) );
end