import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "GuessBuildSystem_Maven"
	when
	    $da : Activity(id == R.id.GuessBuildSystemActivity)
		$fc : FolderArtifact(activity == $da, $poms : getFileNamesForPattern("**/pom.xml"), $poms.length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.MAVEN)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.MAVEN) );
		insert( new FileArtifactList($da, $fc.getDir(), $poms) );
end

rule "GuessBuildSystem_Ant"
	when
	    $da : Activity(id == R.id.GuessBuildSystemActivity)
		$fc : FolderArtifact(activity == $da, getFileNamesForPattern("**/build.xml").length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.ANT)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.ANT) );
end

rule "GuessBuildSystem_Make"
	when
	    $da : Activity(id == R.id.GuessBuildSystemActivity)
		$fc : FolderArtifact(activity == $da, getFileNamesForPattern("**/makefile").length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.MAKE)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.MAKE) );
end

rule "GuessBuildSystem_Other"
		salience -100
	when
	    $da : Activity(id == R.id.GuessBuildCommandActivity)
		$fc : FolderArtifact(activity == $da)
		not BuildSystem()
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.OTHER)	);
end