import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "GuessBuildSystem_Maven"
	when
		$fc : FolderArtifact(id == R.id.OriginalArtifact, $poms : getFileNamesForPattern("**/pom.xml"), $poms.length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.MAVEN)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.MAVEN) );
		insert( new FileArtifactList(R.id.PomFiles, $fc.getDir(), $poms) );
end

rule "GuessBuildSystem_Ant"
	when
		$fc : FolderArtifact(id == R.id.OriginalArtifact && getFileNamesForPattern("**/build.xml").length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.ANT)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.ANT) );
end

rule "GuessBuildSystem_Make"
	when
		$fc : FolderArtifact(id == R.id.OriginalArtifact && getFileNamesForPattern("**/makefile").length > 0)
		not BuildSystem(buildSystem == BuildSystem.BUILD_SYSTEMS.MAKE)
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.MAKE) );
end

rule "GuessBuildSystem_Other"
		salience -100
	when
		$fc : FolderArtifact(id == R.id.OriginalArtifact)
		not BuildSystem()
	then
		insert( new BuildSystem(BuildSystem.BUILD_SYSTEMS.OTHER)	);
end