import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.generic.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.deploy.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.maven.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "Populate deploy folder for GuessRunExecutable activity"
salience 100
	when
		$r : ReqNewActivity( activityName == R.activity.GuessRunExecutable )
		$a : Activity( request == $r )
		$folder : FolderArtifactAlias( request == $r )
		not FolderArtifact( activity == $a )
	then
		insert(new FolderArtifact($a, $folder);
end

rule "Eval full list of files"
	when
		$a : Activity( activityName == R.activity.GuessRunExecutable )
		$folder : FolderArtifact( activity == $a )
	then
		insert( $folder.getFileArtifactListForPattern("**/*") );
		insert( $folder.getFileArtifactListForPattern("**/*.exe") );
		insert( $folder.getFileArtifactListForPattern("**/*.sh") );
		insert( $folder.getFileArtifactListForPattern("**/*.py") );
end

rule "No candidates"
	when
		$a : Activity( activityName == R.activity.GuessRunExecutable )
		$candidates : java.util.LinkedList( size == 0 ) from collect( FileArtifactList(activity == $a, size >= 1) )
	then
		insert( new GenericActivityError($a, R.error.NoExecutableFound) );
end

rule "Ok candidates"
	when
		$a : Activity( activityName == R.activity.GuessRunExecutable )
		$candidates : java.util.LinkedList( size == 1 ) from collect( FileArtifactList(activity == $a, size == 1) )
		not FileArtifactList(activity == $a, size >= 1)
	then
		insert( new GenericActivitySuccess($a) );
		insert( new ExecutableFileArtifact($candidates.get(0).get(0)) );
end

rule "Too many candidates"
	when
		$a : Activity( activityName == R.activity.GuessRunExecutable )
		$candidates : java.util.LinkedList( size > 1 ) from collect( FileArtifactList(activity == $a, size >= 1) )
	then
		insert( new GenericActivityError($a, R.error.TooManyExecutables) );
end

rule "Set run executable"
	when
		$r : ReqNewActivity( activityName == R.activity.GuessRunExecutable )
		$a : Activity( request == $r )
		exists ActivitySucceeded( activity == $a )
		$exec : ExecutableFileArtifact( activity == $a ) )
	then
		insertLogical ( new ExecutableFileArtifactAlias( $r, $exec ) );
end
