import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "GuessSourceLanguage_Java"
	when
		$da : DeployActivity(  )
		$fc : FolderArtifact(activity == $da, getFileNamesForPattern("**/*.java").length > 0)
		not SourceLanguage(sourceLanguage == SourceLanguage.SOURCE_LANGUAGES.JAVA)
	then
		insert( new SourceLanguage(SourceLanguage.SOURCE_LANGUAGES.JAVA) );
end

rule "GuessSourceLanguage_Python"
	when
		$da : DeployActivity(  )
		$fc : FolderArtifact(activity == $da, getFileNamesForPattern("**/*.py").length > 0)
		not SourceLanguage(sourceLanguage == SourceLanguage.SOURCE_LANGUAGES.PYTHON)
	then
		insert( new SourceLanguage(SourceLanguage.SOURCE_LANGUAGES.PYTHON) );
end

rule "GuessSourceLanguage_C_CPP"
	when
		$da : DeployActivity(  )
		$fc : FolderArtifact(activity == $da, getFileNamesForPattern2(new String[]{"**/*.c","**/*.cpp","**/*.h","**/*.hxx"}).length > 0)
		not SourceLanguage(sourceLanguage == SourceLanguage.SOURCE_LANGUAGES.C_CPP)
	then
		insert( new SourceLanguage(SourceLanguage.SOURCE_LANGUAGES.C_CPP) );
end

rule "GuessSourceLanguage_Other"
		salience -100
	when
		$da : DeployActivity(  )
		$fc : FolderArtifact(activity == $da)
		not SourceLanguage()
	then
		insert( new SourceLanguage(SourceLanguage.SOURCE_LANGUAGES.OTHER) );
end