import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.run.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.env.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.deploy.*;

rule "DefaultTmpDir"
	when
		not TmpDirRoot( )
		$dd : DataDirRoot(  )
	then
		insert(new TmpDirRoot(Activity.USER, $dd.getAbsolutePath(), "tmp_" + java.util.UUID.randomUUID().toString())); 
end