import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.requestfacts.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.build.maven.*;
import ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.actionfacts.*;

rule "Cast FolderArtifact"
	when
		$artifact : Artifact( directory == true )
		not FolderArtifact( this == $artifact )
	then
		retract( $artifact );
		insert( new FolderArtifact($artifact) );
end

rule "Cast FileArtifact"
	when
		$artifact : Artifact( directory == false )
		not FileArtifact( this == $artifact )
	then
		retract( $artifact );
		insert( new FileArtifact($artifact) );
end
