
declare MavenFeatureInUse extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.globals.impl.GlobalFactInUseBase
end

declare MavenFeature extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.features.impl.FeatureBase
	cmdName : String
end

declare MavenProjectDir extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.artifact.impl.FolderArtifactBase end
declare MavenTargetDir extends BuildOutputDir end

declare MavenRepoLocation extends ru.spbstu.icc.kspt.kuznetsov.fpf4mir.core.facts.artifact.impl.FolderArtifactBase end
